purchase_nm_model_api_docker_release:
  image: docker-20.10.8
  stage: docker-release
  services:
    - docker:dind
  when: manual
  script:
    - !reference [.python_docker_release, script]
  variables:
    COMPONENT: "-api"
    TAG: "$CI_COMMIT_TAG"
  only:
    - tags

.python_docker_release:
  script:
    - docker login -u $HARBOR_USER -p $HARBOR_TOKEN $HARBOR_URL
    - docker info
    - docker build -t $DOCKER_REGISTRY/$COMPONENT:$TAG -f python/build/docker/$COMPONENT.Dockerfile .
    - docker push $DOCKER_REGISTRY/$COMPONENT:$TAG
